{% set name = "Keras-Preprocessing" %}
{% set version = "1.0.2" %}
{% set sha256 = "64212b715a435b43724ecf26be67a441cee426e3ef614a6326aba06016ba9779" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/keras-team/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-correct-version-number.patch


build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - keras >=2.1.6
    - numpy >=1.9.1
    - scipy >=0.14
    - six >=1.9.0

test:
  imports:
    - keras_preprocessing

about:
  home: https://github.com/keras-team/keras-preprocessing
  license: MIT 
  license_family: MIT
  license_file: LICENSE
  summary: Data preprocessing and data augmentation module of the Keras deep learning library
  description: |
    Keras Preprocessing is the data preprocessing and data augmentation module
    of the Keras deep learning library. It provides utilities for working
    with image data, text data, and sequence data.
  doc_url: https://keras.io/
  dev_url: https://github.com/keras-team/keras-preprocessing

extra:
  recipe-maintainers:
    - CurtLH
    - jjhelmus
