{% set name = "Keras-Preprocessing" %}
{% set version = "1.1.0" %}
{% set sha256 = "26f26354370f4a08a029137630d72870e99e924cd8f6e04c2f6fc0bd86708275" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/keras-team/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.9.1
    - scipy >=0.14
    - six >=1.9.0
  # avoid a direct requirement on keras to prevent a circular dependency
  run_constrained:
    - keras >=2.1.6

test:
  imports:
    - keras_preprocessing

about:
  home: https://github.com/keras-team/keras-preprocessing
  license: MIT 
  license_family: MIT
  license_file: LICENSE
  summary: Data preprocessing and data augmentation module of the Keras deep learning library
  description: |
    Keras Preprocessing is the data preprocessing and data augmentation module
    of the Keras deep learning library. It provides utilities for working
    with image data, text data, and sequence data.
  doc_url: https://keras.io/
  dev_url: https://github.com/keras-team/keras-preprocessing

extra:
  recipe-maintainers:
    - CurtLH
    - h-vetinari
