travis:
  secure:
    BINSTAR_TOKEN: Lanybqfxb3ozzh4DalUek18ASnFMuXdoBvIZmdu/i0C/RTdqPZ8NwoFnbi0EqluiSpDzchYWPWmZzTgvl8wWRVXfFPytdI+CD1/ApSRt1+hpqZa8SS0FO5PX2SaFo4verfVzDDnwL4JOp0nWUiDLrgS4O24dxLPS8DYXirgDlzSqbXUCP3ix4pvTfXbnNUB3V2Ek9MjXaa3EmdTTzx1ObP679Km0R/G6iIfNxOl8i1LnfOrOJPQJpdNupj0+YtgZTPhyKjrVTxcQWJzv8jwgh7by5f5akgLgkGkL4WDNhd3lJAPBx6Mv0v59eJ5diwAAjymo5Q+ut0rCqgX3MiA7f29+DjDaD6nBBPwyJguElW86f2Sj6MBBT4KpDadQ46nFkZBw/F2ezOp5BbmUI4g0ogftvW6998FIktU/Q09EpxAPbEefVzXwjaM5eLQ9Qd6Ld3Av287Pscf5zhURT2h8pXuo3BM/jDH41lomK1hoB5uVvwRn8MlicAxj8OIvOiHrOrlpeEC8KV8G/oWN+ig7TEj181BHIW6+PR6lGEc/8Dc00raHAXcVkVLyKuY/FHbCetPAJtdaDJQJi+7sfVWCvVeg32910KEVYouQRTXKx4SXk3poUUUpONIKBAufw1ef6Kbz7I6H8jZ5TUy+BTCatMjvfBU5poHnPToMEteVrKA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
