travis:
  secure:
    BINSTAR_TOKEN: RAKtCAVXUR/KVVLv75PxRpA/Qzb2qOOq73OHyPnJc62L5Ou25SpVab06oF4Cm1Elv7lLfv2AsbdSYD0Te/l5EIBtav/4oR7IC5hISnN7UFMXsGnS9t1Y1ubm/lnFqcC2UEeZR2HT+bayzs2t/g7vRISruBBaw0awUugrZbcbPe5FU1FxQeVdfnUIQIpDDwIQmzz5XvFOt8N5xZ/RYg3RdKLIgoH7qy+46XNM7Jtwvh/oiQeRnsM8VK1KSaKzDX58y/U6RGAxJErey+OrC2sGYhltAizAW/FXCBVjjnh4/a+fHAyI6Azsws7ZvCrBx6N3LZZgcZnWEmFw+IlEi/ush/fdCq7JgVXW/1bJWYXNECo2x2NitzLRIfXbHUqbgultt6ZC9Flq24HDpsJEsqHCEw5IQiWrngThgTqpjv0UUe6rJqOxGxe3YkfvlfCtoCMIWaQ9vbA/+7TlptKQxHKEBeM/pWGPL0hP3S6vuTB1MNYBNE+Ftqmxo+hOsxYiIGLkJwyoAZyKtDVRdK+ep8ai+M036b91N3nJlmzUk2hmX2s0TC2LxrJPMLvCLwmegzoQoSN/kWqM3hLF0YqQADyaLA66bqCJky8QuzowMiAd/CEkJUhBsCwa4NY/j1PIWPPtaC4IqlTGmmsyvhhpM+V2xZp3BQUrHmPPXLTjtGuLsiM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
